/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c66d2d0a-ac70-4170-994e-cd620f23b611",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4qRi2U62Z",
    "aws_user_pools_web_client_id": "ai2sn2o9cu91sd0g172h29r6u",
    "oauth": {
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://ochre.auth.us-east-1.amazoncognito.com/",
        "redirectSignOut": "https://auth.us-east-1.amazoncognito.com/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
